### ISSUE TITLE
Package fails on publish

### ISSUE THREAD

**Issue by juanpicado** [verdaccio/verdaccio-google-cloud#5]
https://circleci.com/gh/verdaccio/verdaccio-google-cloud/62?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

```
#!/bin/bash -eo pipefail
yarn publish
yarn publish v1.5.1
[1/4] Bumping version...
info Current version: 0.0.8
error An unexpected error occurred: "You must specify a new version with --new-version when running with --non-interactive.".
info If you think this is a bug, please open a bug report with the information provided in "/home/circleci/google-storage/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/publish for documentation about this command.
Exited with code 1
```

**Comment by sergiohgz** [comment]
I found that there is an issue with `yarn publish` command. 

If you want to publish in non interactive mode, you should use `--non-interactive` flag or, if you are in a CI, that will be enabled by default. But that is not the problem.

The real problem is that if you run in non interactive mode, you must specify a version to bump. In yarn@1.8.0 that was fixed, but there is not a official release (it was pre-released).

In this stage, we can do 2 different things:
1. Use `npm publish` as a temporal fix (there are many projects doing this)
2. Try to upgrade the provided yarn version on CircleCI

I prefer the first option until next release of Yarn

[PR](https://github.com/yarnpkg/yarn/pull/5748) that solves the problem.
[Release notes](https://github.com/yarnpkg/yarn/releases/tag/v1.8.0) of yarn@1.8.0
